export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header
          style={{backgroundColor:"lightblue",padding:"1rem"}}>
          <p>This is header</p>
        </header>
        
        {children}

        <footer
          style={{backgroundColor:"green",padding:"1rem"}}>
          <p>This is header</p>
        </footer>
        
        </body>
    </html>
  )
}
